version: '3'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Azerty123
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
