version: '3.7'

services:
  db:
    image: 'mysql:5.7'
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./mysql-data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@db/symfony
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./catalog_pizza:/app
      - ./php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
